server=192.168.0.93
password.api.url=https://192.168.0.93:8443/v1/change-password
shares=0 - Faturamento|1 - Contabilidade|2 - Conta Sucata|3 - Importacao|4 - Documentos Legais|5 - RH|6 - Compras|7 - Formulario e Manual|8 - Relatorio|9 - Arquivamento|10 - Archived|11 - Operacional|12 - Scanner|13 - TI|14 - NFS Interestaduais|15 - Imagens|16 - EHS|17 - Manutenção|18 - Expedição|19 - PAEX|20 - Alerta de Riscos|21 - ABNT|22 - Marketing|23 - Producao
